[tool.poetry]
name = "web-9-main"
version = "0.1.0"
description = "A description of your project"
authors = ["Olena Maliarenko"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"